# -*- coding: utf-8 -*-
"""Find-S algo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DZnWzmdboWLNRR2G8guOoTLz5rL4Di7r
"""

import csv

def updateHypothesis(x, h):
    if h == []:
        return x

    for i in range(0, len(h)):
        if x[i].upper()!=h[i].upper():
            h[i] = '?'

    return h


if __name__ == "__main__":
    data = []
    h = []

    with open('data.csv', 'r') as file:
        reader = csv.reader(file)
        print("Data: ")
        for row in reader:
            data.append(row)
            print(row)

    if data:
        for x in data:
            if x[-1].upper() == "YES":
                x.pop() # removing last field
                h = updateHypothesis(x,h)

    print("\nHypothesis: ",h)